"use client";
import { useCallback, useEffect, useState } from "react";
import { Bell, CheckCheck } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { EmptyState, ErrorState, LoadingState } from "@/components/ui";
import { apiFetch, type Notification } from "@/lib/api";
import { useApp } from "@/components/providers";
import { useWorkspaceRealtimeRefresh } from "@/components/realtime-provider";
export default function InboxPage(){const {workspace}=useApp();const [items,setItems]=useState<Notification[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState("");const load=useCallback(async()=>{if(!workspace)return;setLoading(true);try{setItems(await apiFetch<Notification[]>(`/api/v1/workspaces/${workspace!.id}/notifications`));setError("")}catch(e){setError(e instanceof Error?e.message:"Failed to load notifications")}finally{setLoading(false)}},[workspace]);useEffect(()=>{void load()},[load]);useWorkspaceRealtimeRefresh(workspace?.id,load);if(!workspace)return null;async function markAll(){await apiFetch(`/api/v1/workspaces/${workspace!.id}/notifications/read-all`,{method:"PATCH",body:JSON.stringify({})});await load()}return <AppShell><div className="standard-page"><div className="page-heading"><div><h1>Inbox</h1><p>Assignments, invitations, mentions, due dates, and system events.</p></div><button className="secondary-button" onClick={()=>void markAll()}><CheckCheck size={16}/>Mark all read</button></div>{error?<ErrorState message={error} retry={()=>void load()}/>:loading?<LoadingState/>:items.length===0?<EmptyState title="Inbox is clear" text="New notifications will appear here."/>:<div className="notification-list">{items.map(n=><article className={`notification-card ${n.readAt?"read":"unread"}`} key={n.id}><span className="notification-icon"><Bell size={18}/></span><div><h3>{notificationTitle(n)}</h3><p>{notificationText(n)}</p><small>{new Date(n.createdAt).toLocaleString()}</small></div>{!n.readAt&&<i/>}</article>)}</div>}</div></AppShell>}
function notificationTitle(n:Notification){return n.type.split("_").map(x=>x[0]?.toUpperCase()+x.slice(1)).join(" ")}
function notificationText(n:Notification){if(n.type==="invitation")return "You were invited to a workspace.";if(n.taskId)return `A task event requires your attention (${n.taskId.slice(0,8)}).`;return typeof n.payload.message==="string"?n.payload.message:"Task Genie notification"}
