"use client";
import { useCallback, useEffect, useState } from "react";
import { CalendarDays, Download, MessageCircle, Paperclip, Plus, Send, Star, Trash2, Upload, X } from "lucide-react";
import { API_BASE, apiFetch, descriptionText, formatDate, initials, type Attachment, type Checklist, type Comment, type Status, type Task } from "@/lib/api";
import { Avatar, PriorityBadge, StatusBadge } from "./ui";
import { useRealtime, useRealtimeEvent } from "./realtime-provider";

type Props={workspaceId:string;task:Task|null;onClose?:()=>void;onChanged?:(task?:Task)=>void};
export function LiveTaskDrawer({workspaceId,task,onClose,onChanged}:Props){
 const {subscribeTask,setTaskPresence,taskPresence}=useRealtime();
 const [detail,setDetail]=useState<Task|null>(task),[comments,setComments]=useState<Comment[]>([]),[checklists,setChecklists]=useState<Checklist[]>([]),[attachments,setAttachments]=useState<Attachment[]>([]),[statuses,setStatuses]=useState<Status[]>([]),[comment,setComment]=useState(""),[newItem,setNewItem]=useState(""),[busy,setBusy]=useState(false),[uploadError,setUploadError]=useState("");
 const load=useCallback(async()=>{if(!task)return;const [d,c,l,a,s]=await Promise.all([apiFetch<Task>(`/api/v1/workspaces/${workspaceId}/tasks/${task.id}`),apiFetch<Comment[]>(`/api/v1/workspaces/${workspaceId}/tasks/${task.id}/comments`),apiFetch<Checklist[]>(`/api/v1/workspaces/${workspaceId}/tasks/${task.id}/checklists`),apiFetch<Attachment[]>(`/api/v1/workspaces/${workspaceId}/tasks/${task.id}/attachments`),apiFetch<Status[]>(`/api/v1/workspaces/${workspaceId}/projects/${task.projectId}/statuses`)]);setDetail(d);setComments(c);setChecklists(l);setAttachments(a);setStatuses(s);},[workspaceId,task]);
 useEffect(()=>{if(!task)return;const unsubscribe=subscribeTask(task.id);setTaskPresence("viewing",task.id);return()=>{setTaskPresence("online");unsubscribe();};},[task,subscribeTask,setTaskPresence]);
 useRealtimeEvent((event)=>{if(task&&event.workspaceId===workspaceId&&event.taskId===task.id)void load();});
 useEffect(()=>{setDetail(task);if(task)void load();},[task,load]);
 if(!detail)return null;
 async function patch(payload:Record<string,unknown>){setBusy(true);try{const updated=await apiFetch<Task>(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}`,{method:"PATCH",body:JSON.stringify({...payload,version:detail!.version})});setDetail({...detail,...updated});onChanged?.(updated);await load();}finally{setBusy(false);}}
 async function addComment(){if(!comment.trim())return;await apiFetch(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}/comments`,{method:"POST",body:JSON.stringify({body:comment})});setComment("");await load();}
 async function addChecklistItem(){if(!newItem.trim())return;let list=checklists[0];if(!list){list=await apiFetch<Checklist>(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}/checklists`,{method:"POST",body:JSON.stringify({title:"Checklist"})});}await apiFetch(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}/checklists/${list.id}/items`,{method:"POST",body:JSON.stringify({content:newItem})});setNewItem("");await load();}
 async function upload(file:File){setUploadError("");const fd=new FormData();fd.append("file",file);try{await apiFetch(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}/attachments`,{method:"POST",body:fd});await load();}catch(e){setUploadError(e instanceof Error?e.message:"Upload failed");}}
 const allItems=checklists.flatMap(x=>x.items),completed=allItems.filter(x=>x.isCompleted).length;
 const collaborators=taskPresence(detail.id);
 return <aside className="task-drawer"><div className="drawer-topline"><span>Task Details</span>{onClose&&<button className="icon-button" onClick={onClose}><X size={18}/></button>}</div><div className="drawer-scroll"><div className="task-title-row"><span className="task-color" style={{background:detail.projectColor??"#6d4aff"}}/><h2>{detail.title}</h2><button className="star-button"><Star size={19}/></button></div><div className="task-meta-inline"><span><MessageCircle size={14}/>{comments.length}</span><span><Paperclip size={14}/>{attachments.length}</span><span>#{detail.projectKey}-{detail.number}</span></div>{collaborators.length>0&&<div className="presence-strip"><strong>{collaborators.some(x=>x.state==="editing")?"Editing now":"Viewing now"}</strong><span>{collaborators.map(x=>x.userName).join(", ")}</span><div className="presence-avatars">{collaborators.slice(0,4).map(x=><span key={x.userId}>{initials(x.userName)}</span>)}</div></div>}
 <div className="detail-grid"><span>Status</span><div><select className="inline-select" value={detail.statusId??""} disabled={busy} onChange={e=>void patch({statusId:e.target.value||null,completed:statuses.find(s=>s.id===e.target.value)?.category==="completed"})}><option value="">No status</option>{statuses.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></div><span>Priority</span><div><select className="inline-select" value={detail.priority} disabled={busy} onChange={e=>void patch({priority:e.target.value})}><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Medium</option><option value="low">Low</option><option value="none">None</option></select></div><span>Assignee</span><div className="assignee-value">{detail.assignees?.[0]?<><Avatar initials={initials(detail.assignees[0].name)} size="sm"/>{detail.assignees[0].name}</>:"Unassigned"}</div><span>Due Date</span><div><CalendarDays size={14}/>{formatDate(detail.dueAt)}</div><span>Labels</span><div className="label-list">{detail.labels?.map(label=><b key={label.id} style={{color:label.color}}>{label.name}</b>)}</div></div>
 <Section title="Checklist" count={`${completed} / ${allItems.length}`}><div className="checklist">{allItems.map(item=><label key={item.id}><input type="checkbox" checked={item.isCompleted} onChange={e=>void apiFetch(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}/checklist-items/${item.id}`,{method:"PATCH",body:JSON.stringify({isCompleted:e.target.checked})}).then(load)}/><span>{item.content}</span></label>)}</div><div className="inline-add"><input value={newItem} onChange={e=>setNewItem(e.target.value)} placeholder="Add checklist item" onKeyDown={e=>{if(e.key==="Enter")void addChecklistItem();}}/><button onClick={()=>void addChecklistItem()}><Plus size={14}/></button></div></Section>
 <Section title="Description"><p className="description-text">{descriptionText(detail)}</p></Section>
 <Section title="Attachments" count={String(attachments.length)}><div className="attachment-list">{attachments.map(file=><div className="attachment-row" key={file.id}><span className="file-kind file-doc">FILE</span><span><strong>{file.originalName}</strong><small>{Math.ceil(file.sizeBytes/1024)} KB · <em className={file.scanStatus==="clean"?"scan-clean":"scan-warning"}>{file.scanStatus==="clean"?"ClamAV clean":file.scanStatus??"Scanned"}</em></small></span><a className="icon-button" href={`${API_BASE}/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}/attachments/${file.id}/download`}><Download size={16}/></a></div>)}</div>{uploadError&&<p className="form-error">{uploadError}</p>}<label className="mini-action"><Upload size={14}/>Add attachment<input hidden type="file" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f);e.currentTarget.value="";}}/></label></Section>
 <Section title="Comments" count={String(comments.length)}>{comments.map(c=><div className="comment-row" key={c.id}><Avatar initials={initials(c.authorName)} size="sm"/><p><strong>{c.authorName}</strong><span>{c.body.text}</span></p><time>{new Date(c.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</time></div>)}<div className="comment-box"><Avatar initials="ME" tone="tone-rose" size="sm"/><input value={comment} onChange={e=>setComment(e.target.value)} onFocus={()=>setTaskPresence("editing",detail.id)} onBlur={()=>setTaskPresence("viewing",detail.id)} placeholder="Add a comment..." onKeyDown={e=>{if(e.key==="Enter")void addComment();}}/><button onClick={()=>void addComment()}><Send size={16}/></button></div></Section>
 <button className="danger-button drawer-delete" onClick={()=>{if(confirm("Delete this task?"))void apiFetch(`/api/v1/workspaces/${workspaceId}/tasks/${detail!.id}`,{method:"DELETE"}).then(()=>onChanged?.());}}><Trash2 size={15}/>Delete task</button></div></aside>;
}
function Section({title,count,children}:{title:string;count?:string;children:React.ReactNode}){return <section className="drawer-section"><div className="drawer-section-title"><strong>{title}</strong><span>{count}</span></div>{children}</section>}
