"use client";
import { useEffect, useMemo, useState } from "react";
import { apiFetch, descriptionText, type Label, type Member, type Project, type Status, type Task } from "@/lib/api";
import { Modal } from "./ui";

type Props={open:boolean;workspaceId:string;task?:Task|null;initialProjectId?:string;onClose:()=>void;onSaved:(task:Task)=>void};
export function TaskForm({open,workspaceId,task,initialProjectId,onClose,onSaved}:Props){
 const [projects,setProjects]=useState<Project[]>([]),[members,setMembers]=useState<Member[]>([]),[labels,setLabels]=useState<Label[]>([]),[statuses,setStatuses]=useState<Status[]>([]);
 const [projectId,setProjectId]=useState(task?.projectId??initialProjectId??""),[title,setTitle]=useState(task?.title??""),[description,setDescription]=useState(descriptionText(task)),[statusId,setStatusId]=useState(task?.statusId??""),[priority,setPriority]=useState<Task["priority"]>(task?.priority??"normal"),[dueAt,setDueAt]=useState(task?.dueAt?.slice(0,10)??""),[assigneeIds,setAssigneeIds]=useState<string[]>(task?.assignees?.map(x=>x.userId)??[]),[labelIds,setLabelIds]=useState<string[]>(task?.labels?.map(x=>x.id)??[]),[saving,setSaving]=useState(false),[error,setError]=useState("");
 useEffect(()=>{if(!open)return;void Promise.all([apiFetch<Project[]>(`/api/v1/workspaces/${workspaceId}/projects`),apiFetch<Member[]>(`/api/v1/workspaces/${workspaceId}/members`),apiFetch<Label[]>(`/api/v1/workspaces/${workspaceId}/labels`)]).then(([p,m,l])=>{setProjects(p);setMembers(m);setLabels(l);const next=task?.projectId??initialProjectId??p[0]?.id??"";setProjectId(next);}).catch(e=>setError(e instanceof Error?e.message:"Failed to load form"));},[open,workspaceId,task,initialProjectId]);
 useEffect(()=>{if(!projectId)return;void apiFetch<Status[]>(`/api/v1/workspaces/${workspaceId}/projects/${projectId}/statuses`).then(s=>{setStatuses(s);if(!statusId)setStatusId(s.find(x=>x.isDefault)?.id??s[0]?.id??"");}).catch(()=>setStatuses([]));},[workspaceId,projectId,statusId]);
 useEffect(()=>{if(!open)return;setTitle(task?.title??"");setDescription(descriptionText(task));setStatusId(task?.statusId??"");setPriority(task?.priority??"normal");setDueAt(task?.dueAt?.slice(0,10)??"");setAssigneeIds(task?.assignees?.map(x=>x.userId)??[]);setLabelIds(task?.labels?.map(x=>x.id)??[]);setError("");},[open,task]);
 const canSave=useMemo(()=>title.trim()&&projectId&&!saving,[title,projectId,saving]);
 async function submit(e:React.FormEvent){e.preventDefault();if(!canSave)return;setSaving(true);setError("");try{const payload={title:title.trim(),description,priority,statusId:statusId||null,dueAt:dueAt?new Date(`${dueAt}T17:00:00`).toISOString():null,assigneeIds,labelIds,...(!task?{projectId}:{}),...(task?{version:task.version}:{})};const saved=await apiFetch<Task>(task?`/api/v1/workspaces/${workspaceId}/tasks/${task.id}`:`/api/v1/workspaces/${workspaceId}/tasks`,{method:task?"PATCH":"POST",body:JSON.stringify(payload)});onSaved(saved);onClose();}catch(e){setError(e instanceof Error?e.message:"Save failed");}finally{setSaving(false);}}
 return <Modal open={open} title={task?"Edit task":"Create task"} onClose={onClose}><form className="form-stack" onSubmit={submit}>{error&&<p className="form-error">{error}</p>}<label>Project<select value={projectId} disabled={Boolean(task)} onChange={e=>{setProjectId(e.target.value);setStatusId("");}}>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Task title<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required maxLength={500}/></label><label>Description<textarea rows={5} value={description} onChange={e=>setDescription(e.target.value)}/></label><div className="form-grid"><label>Status<select value={statusId} onChange={e=>setStatusId(e.target.value)}><option value="">No status</option>{statuses.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Priority<select value={priority} onChange={e=>setPriority(e.target.value as Task["priority"])}><option value="urgent">Urgent</option><option value="high">High</option><option value="normal">Medium</option><option value="low">Low</option><option value="none">None</option></select></label><label>Due date<input type="date" value={dueAt} onChange={e=>setDueAt(e.target.value)}/></label></div><fieldset><legend>Assignees</legend><div className="choice-grid">{members.filter(m=>m.status==="active").map(m=><label className="choice" key={m.userId}><input type="checkbox" checked={assigneeIds.includes(m.userId)} onChange={e=>setAssigneeIds(v=>e.target.checked?[...v,m.userId]:v.filter(id=>id!==m.userId))}/>{m.name}</label>)}</div></fieldset><fieldset><legend>Labels</legend><div className="choice-grid">{labels.map(l=><label className="choice" key={l.id}><input type="checkbox" checked={labelIds.includes(l.id)} onChange={e=>setLabelIds(v=>e.target.checked?[...v,l.id]:v.filter(id=>id!==l.id))}/><span className="project-dot" style={{background:l.color}}/>{l.name}</label>)}</div></fieldset><div className="form-actions"><button type="button" className="secondary-button" onClick={onClose}>Cancel</button><button className="primary-button" disabled={!canSave}>{saving?"Saving…":task?"Save changes":"Create task"}</button></div></form></Modal>;
}
