import type { HTMLAttributes, ReactNode } from "react";
export function Avatar({ initials, tone = "tone-violet", size = "md" }: { initials: string; tone?: string; size?: "sm" | "md" | "lg" }) { return <span className={`avatar ${tone} avatar-${size}`}>{initials}</span>; }
export function StatusBadge({ value }: { value: string }) { const slug = value.toLowerCase().replaceAll(" ", "-"); return <span className={`badge badge-${slug}`}>{value}</span>; }
export function PriorityBadge({ value }: { value: string }) { const label = value === "normal" ? "Medium" : value === "none" ? "None" : value[0]?.toUpperCase()+value.slice(1); return <span className={`priority priority-${value}`}>{value === "low" ? "↓" : value === "none" ? "–" : "↑"} {label}</span>; }
export function Progress({ value, compact = false }: { value: number; compact?: boolean }) { return <div className={`progress-wrap ${compact ? "compact" : ""}`}>{!compact && <span>{value}%</span>}<span className="progress-track"><span style={{ width: `${Math.max(0,Math.min(100,value))}%` }} /></span></div>; }
export function Card({ children, className = "", ...props }: HTMLAttributes<HTMLElement> & { children: ReactNode }) { return <section className={`card ${className}`} {...props}>{children}</section>; }
export function LoadingState({ label = "Loading…" }: { label?: string }) { return <div className="state-panel"><span className="spinner"/><p>{label}</p></div>; }
export function EmptyState({ title, text, action }: { title: string; text: string; action?: ReactNode }) { return <div className="state-panel empty-state"><h3>{title}</h3><p>{text}</p>{action}</div>; }
export function ErrorState({ message, retry }: { message: string; retry?: () => void }) { return <div className="state-panel error-state"><h3>Something broke</h3><p>{message}</p>{retry && <button className="secondary-button" onClick={retry}>Retry</button>}</div>; }
export function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { if (!open) return null; return <div className="modal-backdrop" role="presentation" onMouseDown={(e)=>{if(e.target===e.currentTarget)onClose();}}><section className="modal-card" role="dialog" aria-modal="true"><div className="modal-title"><h2>{title}</h2><button className="icon-button" onClick={onClose}>×</button></div>{children}</section></div>; }
